# OpenCloudTouch Supporters API — Deployment Script
#
# Prerequisites: WinSCP installed (https://winscp.net/eng/download.php)
# Usage: .\deploy-supporters-api.ps1

param(
    [string]$PropertiesFile = "deploy.properties",
    [switch]$UploadCSV = $false,
    [switch]$Test = $false
)

$ErrorActionPreference = "Stop"

Write-Host "=== OpenCloudTouch Supporters API Deployment ===" -ForegroundColor Cyan
Write-Host ""

# Check if properties file exists
if (-not (Test-Path $PropertiesFile)) {
    Write-Host "❌ Properties file not found: $PropertiesFile" -ForegroundColor Red
    Write-Host "   Copy deploy.properties.example to deploy.properties and fill in your credentials." -ForegroundColor Yellow
    exit 1
}

# Parse properties file
Write-Host "📄 Loading configuration from $PropertiesFile..." -ForegroundColor Yellow
$config = @{}
Get-Content $PropertiesFile | Where-Object { $_ -match '^\s*[^#]' -and $_ -match '=' } | ForEach-Object {
    $key, $value = $_ -split '=', 2
    $config[$key.Trim()] = $value.Trim()
}

# Validate required properties
$required = @('ftp.host', 'ftp.user', 'ftp.pass', 'ftp.path', 'bmc.webhook.secret', 'api.user', 'api.pass')
$missing = $required | Where-Object { -not $config.ContainsKey($_) }
if ($missing) {
    Write-Host "❌ Missing required properties: $($missing -join ', ')" -ForegroundColor Red
    exit 1
}

Write-Host "✅ Configuration loaded" -ForegroundColor Green
Write-Host "   FTP Host: $($config['ftp.host'])" -ForegroundColor Gray
Write-Host "   FTP Path: $($config['ftp.path'])" -ForegroundColor Gray
Write-Host ""

# Generate .env.php
Write-Host "🔐 Generating .env.php with secrets..." -ForegroundColor Yellow
$envPhp = @"
<?php
/**
 * Configuration for Supporters API
 * Generated by deploy-supporters-api.ps1
 * DO NOT EDIT MANUALLY - regenerate with deploy script
 */

// BuyMeACoffee Webhook Secret
define('BMC_WEBHOOK_SECRET', '$($config['bmc.webhook.secret'])');

// Basic Auth credentials for get.php and upload.php
define('API_USER', '$($config['api.user'])');
define('API_PASS', '$($config['api.pass'])');
"@

$envPhpPath = Join-Path $PSScriptRoot ".env.php"
$envPhp | Out-File -FilePath $envPhpPath -Encoding UTF8 -NoNewline
Write-Host "✅ Generated .env.php" -ForegroundColor Green
Write-Host ""

# Check WinSCP
$winscpPath = "C:\Program Files (x86)\WinSCP\WinSCP.com"
if (-not (Test-Path $winscpPath)) {
    Write-Host "❌ WinSCP not found at $winscpPath" -ForegroundColor Red
    Write-Host "   Download from: https://winscp.net/eng/download.php" -ForegroundColor Yellow
    Write-Host "   Or install with: winget install WinSCP.WinSCP" -ForegroundColor Yellow
    exit 1
}

# Upload files via FTP
Write-Host "📤 Uploading files to $($config['ftp.host'])..." -ForegroundColor Yellow

$filesToUpload = @(
    "webhook.php",
    "get.php",
    "upload.php",
    ".htaccess",
    ".env.php"
)

if ($UploadCSV -and (Test-Path "..\..\..\..\apps\frontend\public\supporters.csv")) {
    $filesToUpload += "..\..\..\..\apps\frontend\public\supporters.csv"
}

# Generate WinSCP script
$winscpScript = @"
option batch abort
option confirm off
open ftp://$($config['ftp.user']):$($config['ftp.pass'])@$($config['ftp.host'])
cd $($config['ftp.path'])
"@

foreach ($file in $filesToUpload) {
    $localPath = Join-Path $PSScriptRoot $file
    if (Test-Path $localPath) {
        $filename = Split-Path $file -Leaf
        $winscpScript += "`nput `"$localPath`" `"$filename`""
        Write-Host "   → $filename" -ForegroundColor Gray
    }
}

$winscpScript += "`nexit"

$winscpScriptPath = Join-Path $env:TEMP "winscp-deploy.txt"
$winscpScript | Out-File -FilePath $winscpScriptPath -Encoding ASCII

# Execute WinSCP
try {
    & $winscpPath /script=$winscpScriptPath /log=$env:TEMP\winscp.log
    if ($LASTEXITCODE -eq 0) {
        Write-Host "✅ Files uploaded successfully" -ForegroundColor Green
    } else {
        Write-Host "❌ Upload failed (exit code: $LASTEXITCODE)" -ForegroundColor Red
        Write-Host "   Check log: $env:TEMP\winscp.log" -ForegroundColor Yellow
        exit 1
    }
} finally {
    Remove-Item $winscpScriptPath -ErrorAction SilentlyContinue
}

Write-Host ""

# Cleanup local .env.php
Remove-Item $envPhpPath -Force -ErrorAction SilentlyContinue

# Test API
if ($Test) {
    Write-Host "🧪 Testing API endpoints..." -ForegroundColor Yellow

    # Test download
    $apiUrl = "https://$($config['ftp.host'].Replace('ftp.', ''))/api/supporters/get.php"
    $auth = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes("$($config['api.user']):$($config['api.pass'])"))

    try {
        $response = Invoke-WebRequest -Uri $apiUrl -Headers @{Authorization="Basic $auth"} -UseBasicParsing
        $lines = ($response.Content -split "`n").Count
        Write-Host "   ✅ GET endpoint works ($lines lines)" -ForegroundColor Green
    } catch {
        if ($_.Exception.Response.StatusCode -eq 404) {
            Write-Host "   ⚠️  No supporters.csv yet (404) - run with -UploadCSV to upload initial data" -ForegroundColor Yellow
        } else {
            Write-Host "   ❌ GET failed: $($_.Exception.Message)" -ForegroundColor Red
        }
    }

    Write-Host ""
}

# Summary
Write-Host "=== Deployment Complete ===" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "  1. Configure BMC Webhook:" -ForegroundColor White
Write-Host "     URL: https://$($config['ftp.host'].Replace('ftp.', ''))/api/supporters/webhook.php" -ForegroundColor Gray
Write-Host "     Secret: (already configured in .env.php)" -ForegroundColor Gray
Write-Host ""
Write-Host "  2. Test webhook:" -ForegroundColor White
Write-Host "     Use 'Send Test Event' button in BMC Dashboard" -ForegroundColor Gray
Write-Host ""
Write-Host "  3. Add GitHub Secrets:" -ForegroundColor White
Write-Host "     SUPPORTERS_API_USER = $($config['api.user'])" -ForegroundColor Gray
Write-Host "     SUPPORTERS_API_PASS = ********" -ForegroundColor Gray
Write-Host ""

if (-not $UploadCSV) {
    Write-Host "  4. Upload initial CSV:" -ForegroundColor White
    Write-Host "     .\deploy-supporters-api.ps1 -UploadCSV" -ForegroundColor Gray
    Write-Host ""
}
